import React from 'react';
import {registerRoot,Composition,AbsoluteFill,Sequence,Audio,useCurrentFrame,interpolate} from 'remotion';
import {dimensions} from '../../assets/video-core.mjs';
function Scene({scene,index,width}){
  const frame=useCurrentFrame();const y=interpolate(frame,[0,18],[40,0],{extrapolateRight:'clamp'}),opacity=interpolate(frame,[0,12],[0,1],{extrapolateRight:'clamp'});
  return <AbsoluteFill style={{background:'#10131b',color:'white',padding:width*.08,fontFamily:'Arial, Noto Sans CJK SC, sans-serif',overflow:'hidden'}}><div style={{position:'absolute',width:'65%',aspectRatio:'1',border:'2px solid #a4ff78',borderRadius:'50%',right:'-22%',top:'-8%',opacity:.3,transform:`rotate(${frame/8}deg)`}}/><div style={{fontSize:width*.025,color:'#a4ff78',letterSpacing:4}}>HAOWORD / STUDIO · {String(index+1).padStart(2,'0')}</div><div style={{opacity,transform:`translateY(${y}px)`}}><h1 style={{fontSize:width*.08,lineHeight:1.16,marginTop:'22%',overflowWrap:'anywhere'}}>{scene.heading}</h1><div style={{width:90,height:8,background:'#a4ff78'}}/><p style={{fontSize:width*.035,lineHeight:1.7,color:'#bcc3d2',overflowWrap:'anywhere'}}>{scene.narration}</p></div>{scene.audio&&<Audio src={scene.audio}/>}</AbsoluteFill>;
}
function Video(props){const {width}=dimensions(props.ratio);let from=0;return <AbsoluteFill>{props.scenes.map((s,i)=>{const at=from,duration=Math.ceil(s.duration*30);from+=duration;return <Sequence key={i} from={at} durationInFrames={duration}><Scene scene={s} index={i} width={width}/></Sequence>;})}{props.captions&&(props.alignment||[]).map((c,i)=><Sequence key={`caption-${i}`} from={Math.round(c.start*30)} durationInFrames={Math.max(1,Math.round((c.end-c.start)*30))}><AbsoluteFill style={{justifyContent:'flex-end',alignItems:'center',paddingBottom:'9%'}}><div style={{fontFamily:'Arial, Noto Sans CJK SC, sans-serif',width:'84%',padding:18,background:'#030509e8',borderRadius:12,textAlign:'center',fontSize:width*.043,color:'#a4ff78'}}>{c.text}</div></AbsoluteFill></Sequence>)}</AbsoluteFill>;}
function Root(){return <Composition id="Studio" component={Video} fps={30} width={720} height={1280} durationInFrames={90} defaultProps={{ratio:'9:16',scenes:[]}} calculateMetadata={({props})=>({...dimensions(props.ratio),durationInFrames:Math.max(1,props.scenes.reduce((n,s)=>n+Math.ceil(s.duration*30),0))})}/>;}
registerRoot(Root);
