import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomBytes} from 'node:crypto';
import {openStore,vault} from '../store.mjs';import {enqueue} from '../queue.mjs';import {processTarget} from '../worker.mjs';import {createMeta,ProviderError} from '../meta.mjs';import {createApp} from '../server.mjs';
function fixture(t){const dataDir=mkdtempSync(join(tmpdir(),'publisher-test-'));const db=openStore(dataDir),key=randomBytes(32).toString('base64'),crypt=vault(key);t.after(()=>{db.close();rmSync(dataDir,{recursive:true,force:true});});
for(const id of ['u1','u2'])db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(id,id,'unused',1);
for(const [id,owner,platform] of [['a1','u1','facebook'],['a2','u1','instagram'],['a3','u2','facebook']])db.prepare('INSERT INTO accounts VALUES(?,?,?,?,?,?,?,?,?)').run(id,owner,platform,id,id,'ready',crypt.seal({token:'secret'},id),1,1);
db.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?)').run('v1','u1','a.mp4',12,'sha','ready',1);
return {db,crypt,dataDir,env:{PUBLIC_ORIGIN:'https://publisher.example',PUBLISHER_ENCRYPTION_KEY:key}};}
const request=()=>({key:'request-123',accounts:['a1','a2'],variants:{default:{assetId:'v1',title:'Demo',description:'https://haowordtool.com'}},confirmPublic:true});
test('encrypted credentials cannot be moved to another account',()=>{const c=vault(randomBytes(32).toString('base64'));const sealed=c.seal({token:'private'},'one');assert(!sealed.includes('private'));assert.throws(()=>c.open(sealed,'two'));assert.equal(c.open(sealed,'one').token,'private');});
test('fan-out reuses asset, idempotent request, owner isolation and atomic rollback',t=>{const {db}=fixture(t),r=request(),id=enqueue(db,'u1',r);assert.equal(enqueue(db,'u1',r),id);assert.equal(db.prepare('SELECT count(*) n FROM targets').get().n,2);assert.equal(db.prepare('SELECT count(DISTINCT asset_id) n FROM targets').get().n,1);assert.throws(()=>enqueue(db,'u1',{...r,accounts:['a1']}));assert.throws(()=>enqueue(db,'u1',{...r,key:'another-key',accounts:['a1','a3']}));assert.equal(db.prepare('SELECT count(*) n FROM jobs').get().n,1);assert.throws(()=>enqueue(db,'u2',{...r,key:'other-key',accounts:['a3']}));assert.throws(()=>enqueue(db,'u1',{...r,key:'no-consent',confirmPublic:false}));});
test('uncertain provider result is never retried by worker',async t=>{const f=fixture(t);enqueue(f.db,'u1',{...request(),accounts:['a1']});let calls=0;const meta={check:async()=>true,publish:async()=>{calls++;throw new ProviderError('lost response',{uncertain:true});}};assert(await processTarget({...f,meta}));assert.equal(f.db.prepare('SELECT status FROM targets').get().status,'review_required');assert.equal(await processTarget({...f,meta}),false);assert.equal(calls,1);});
test('Meta Instagram waits for processing then publishes once',async()=>{const calls=[];const responses=[{id:'container'},{status_code:'IN_PROGRESS'},{status_code:'FINISHED'},{id:'post'},{permalink:'https://www.instagram.com/p/test/'}];const meta=createMeta({env:{META_GRAPH_VERSION:'v99.0',PUBLIC_ORIGIN:'https://example.com'},sleep:async()=>{},fetcher:async(url,opt)=>{calls.push({url:String(url),opt});return {ok:true,json:async()=>responses.shift()};}});const result=await meta.publish({remote_id:'ig',platform:'instagram'},{token:'private'},'https://example.com/media',{title:'x',description:'demo'});assert.equal(result.status,'published');assert.equal(calls.filter(c=>c.url.endsWith('/media_publish')).length,1);assert(calls.every(c=>!c.url.includes('private')));});
test('HTTP login, CSRF protection, upload and one-use OAuth state',async t=>{
const dir=mkdtempSync(join(tmpdir(),'publisher-http-')),env={PUBLIC_ORIGIN:'http://localhost:8789',PUBLISHER_DATA_DIR:dir,PUBLISHER_ENCRYPTION_KEY:randomBytes(32).toString('base64'),PUBLISHER_ADMIN_EMAIL:'owner@example.com',PUBLISHER_ADMIN_PASSWORD:'a-long-test-password'};
let exchanges=0;const app=createApp(env,{meta:{authorize:s=>`https://example.com/?state=${s}`,exchange:async()=>{exchanges++;return [{platform:'facebook',remoteId:'page',label:'My page',secret:{token:'secret'}}];}}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;
t.after(async()=>{await new Promise(r=>app.server.close(r));app.db.close();rmSync(dir,{recursive:true,force:true});});
const login={method:'POST',headers:{'Content-Type':'application/json',Origin:env.PUBLIC_ORIGIN},body:JSON.stringify({email:env.PUBLISHER_ADMIN_EMAIL,password:env.PUBLISHER_ADMIN_PASSWORD})};assert.equal((await fetch(base+'/api/publisher/login',{...login,headers:{Origin:'https://evil.example'}})).status,403);
const res=await fetch(base+'/api/publisher/login',login);assert.equal(res.status,200);const cookie=res.headers.get('set-cookie').split(';')[0],headers={Cookie:cookie,Origin:env.PUBLIC_ORIGIN};assert.equal((await fetch(base+'/api/publisher/state',{headers})).status,200);
const video=Buffer.from([0,0,0,12,102,116,121,112,105,115,111,109]);const upload=await fetch(base+'/api/publisher/upload',{method:'POST',headers:{...headers,'Content-Type':'video/mp4'},body:video});assert.equal(upload.status,201);
const auth=await (await fetch(base+'/api/publisher/oauth/meta',{method:'POST',headers})).json();const state=new URL(auth.url).searchParams.get('state');const callback=`${base}/api/publisher/oauth/meta/callback?code=test&state=${state}`;
assert.equal((await fetch(callback,{headers,redirect:'manual'})).status,303);assert.equal((await fetch(callback,{headers,redirect:'manual'})).status,400);assert.equal(exchanges,1);
const accounts=await (await fetch(base+'/api/publisher/state',{headers})).text();assert(!accounts.includes('secret'));assert(accounts.includes('My page'));
});
